plugins {
    id 'java'
}

group = 'com.sofka.automation'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.seleniumhq.selenium:selenium-java:4.18.1'
    implementation 'io.github.bonigarcia:webdrivermanager:6.1.0'

    testImplementation 'io.cucumber:cucumber-java:7.15.0'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.15.0'
    testImplementation 'org.junit.platform:junit-platform-suite:1.10.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.assertj:assertj-core:3.27.7'
}

test {
    useJUnitPlatform()
    systemProperty "cucumber.plugin", "pretty,html:build/reports/cucumber.html"
    systemProperty "cucumber.features", "src/test/resources/features"
    systemProperty "cucumber.glue", "com.sofka.automation.stepdefinitions"
}
