services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: sofkian-rabbitmq
    ports:
      - "5672:5672"   # AMQP (app)
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - sofkian-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  rabbitmq_data:
    name: rabbitmq_data

networks:
  sofkian-net:
    name: sofkian-net
    driver: bridge
