spring.application.name=producer-api

server.port=8082

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.exchange=kudos.exchange
app.rabbitmq.queue=kudos.queue
app.rabbitmq.routing-key=kudos.key

springdoc.swagger-ui.path=/swagger-ui

# Disable default static resource mappings (API-only service)
spring.web.resources.add-mappings=false
